### ISSUE TITLE
UI issue for VxLAN

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#13]
Hi,

I was debugging my TG, and it turns out that I need the ARP Reply feature. Otherwise my switch cannot do the ARP and gets the MAC address of the TG ports for return traffic. I pulled down the latest version (2.2.0), and seems the UI is broken for VxLAN config? It shows VLAN config in VxLAN section:

![issue](https://github.com/uni-tue-kn/P4TG/assets/9436025/7ae05204-c233-4368-ba4d-eb581ddfc14f)

Regards,
Yichen

**Comment by NE4Y** [comment]
Oh yes, you are right ... during refactoring, I accidentally exported VxLAN from VLAN and not from VxLAN in the GUI ... corrected in [22557d1](https://github.com/uni-tue-kn/P4TG/commit/22557d14e87085db9524c47873700210e78a6221) on dev

**Comment by yicwang** [comment]
Now works! Thanks a lot for the quick fix!
