### ISSUE TITLE
Rate is not expected?

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#15]
Hi,

I finally got the end-to-end working, and trying to push some traffic. I see an interesting thing and I think that might be a bug?

I configured 6 ports, and with 40Gbps traffic each on CBR mode:
![config](https://github.com/uni-tue-kn/P4TG/assets/9436025/7b3485f2-0cce-49f5-bb63-8642d5d79e5d)
So I supposed to get 40 * 6 = 240Gbps traffic total.

When I start the traffic, for the first 1 min:
![image](https://github.com/uni-tue-kn/P4TG/assets/9436025/6a10736e-d812-4dc3-8146-119eae86b515)
The traffic is only like half around 120Gbps

After 1 min, the rate goes up to 240Gbps as expected, and shows a spike at picture:
![image](https://github.com/uni-tue-kn/P4TG/assets/9436025/3a88379c-7a21-4a3e-8988-92133c9bf291)

Even though the rate is expected now, but the picture continues to be around 120Gbps.

Thanks very much!

Regards,
Yichen

**Comment by NE4Y** [comment]
Hi,

could you test with Rate Precision mode instead of IAT Precision? I can't reproduce it on my side. 

![Bildschirmfoto 2024-03-14 um 07 01 53](https://github.com/uni-tue-kn/P4TG/assets/7404984/1be37d2e-2c80-4311-8546-aad9aff86309)
![Bildschirmfoto 2024-03-14 um 07 02 20](https://github.com/uni-tue-kn/P4TG/assets/7404984/902b33ff-26dc-4480-ac74-1c8cbe1c0918)

Do the individual rates add up in the tabs?

**Comment by yicwang** [comment]
Same issue with rate precision mode. One thing I do notice is, my UI, that Status says: "Error", but I don't know what really the error is. I also tried to dump the API output, and I do see:
    "tx_rate_l2": {
        "256": 0,
        "260": 0,
        "264": 0,
        "268": 33921951066.66481,
        "272": 33921951066.66481,
        "276": 33921951066.66481,
        "280": 0,
        "284": 0,
        "288": 0,
        "292": 0
    },
    "rx_rate_l2": {
        "256": 0,
        "260": 0,
        "264": 0,
        "268": 33921951893.076653,
        "272": 33921951892.87073,
        "276": 33921951845.8763,
        "280": 0,
        "284": 0,
        "288": 0,
        "292": 0
    },
Meaning, when the issue is there, only 3 out of 6 ports are really TX/RX traffic. Where can I know what exactly the "Error" is complaining?

Regards,
Yichen

**Comment by yicwang** [comment]
After running for some time (after the spike), the API returns good:
    "tx_rate_l2": {
        "256": 33841061396.931564,
        "260": 33841061402.495193,
        "264": 33841061397.66425,
        "268": 33921952511.32681,
        "272": 33921949100.78051,
        "276": 33921951693.307285,
        "280": 0,
        "284": 0,
        "288": 0,
        "292": 0
    },
But the picture is not updated to right scale, and the status still says: "Error"

Regards,
Yichen

**Comment by NE4Y** [comment]
The Status: Error means that there is packet loss / reordering. Could you show the whole dump of /api/statistics and/or the whole UI screen?

Does the controller output something in the command line when you start the traffic gen? Could you also show the content of GET /api/trafficgen

**Comment by yicwang** [comment]
[api_statistics.json](https://github.com/uni-tue-kn/P4TG/files/14597931/api_statistics.json)

[api_trafficgen.json](https://github.com/uni-tue-kn/P4TG/files/14597932/api_trafficgen.json)

![ui](https://github.com/uni-tue-kn/P4TG/assets/9436025/9729d6f8-edf3-42bc-bef1-484164468248)
Note that the out of orders might be totally expected based on the protocol I am testing on.

The controller logs seems to be fine, didn't see anything suspicious:
[2024-03-14T06:26:03Z INFO  p4tg_controller::core::frame_size_monitor] Configure table egress.frame_size_monitor.
[2024-03-14T06:26:03Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.frame_type_monitor.
[2024-03-14T06:26:03Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.ethernet_type_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_size_monitor] Configure table egress.frame_size_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.frame_type_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.ethernet_type_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_size_monitor] Configure table egress.frame_size_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.frame_type_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::frame_type_monitor] Configure table ingress.p4tg.frame_type.ethernet_type_monitor.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::traffic_gen] Calculated traffic generation for stream #1. #5 packets per 134 ns. Rate: 40 Gbps. Accuracy: 100.00%.
[2024-03-14T06:26:07Z INFO  p4tg_controller::core::traffic_gen] Configure table egress.header_replace.header_replace, egress.header_replace.vlan_header_replace, & egress.header_replace.mpls_rewrite_c.mpls_header_replace.
[2024-03-14T06:26:07Z INFO  p4tg_controller::api::traffic_gen] Traffic generation started.
[2024-03-14T06:34:43Z INFO  p4tg_controller::api::traffic_gen] Traffic generation stopped.

For now, my topology is a round trip from P4TG -> Commercial Switch -> DUT -> Commercial Switch -> P4TG. Since the problem is really on the TX side, so I guess it has to be the P4TG's problem. (shouldn't be HW issue??)

Regards,
Yichen

**Comment by yicwang** [comment]
Also, I checked the raw Tofino counter:
bf-sde> pm show
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
PORT |MAC |D_P|P/PT|SPEED  |FEC |AN|KR|RDY|ADM|OPR|LPBK    |FRAMES RX       |FRAMES TX       |E
-----+----+---+----+-------+----+--+--+---+---+---+--------+----------------+----------------+-
1/0  |47/0|256|2/ 0|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80837084742|     81235894897|
2/0  |46/0|260|2/ 4|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80577716651|     81235919983|
3/0  |45/0|264|2/ 8|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80514815282|     81235948406|
4/0  |44/0|268|2/12|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80037958508|     81235975538|
5/0  |43/0|272|2/16|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80780483367|     81236002032|
6/0  |42/0|276|2/20|100G   | RS |Au|Au|YES|ENB|UP |  NONE  |     80659610659|     81236029383|
The packets are actually in-place in all ports, and correct. Not sure why P4TG is only seeing 3/6 ports at half.

Regards,
Yichen

**Comment by NE4Y** [comment]
Okay, i think i know what the problem is.

To verify. Could you change in https://github.com/uni-tue-kn/P4TG/blob/4e98650fb51be319ead0a8b78458f9f1a7d8b13e/Controller/src/core/rate_monitor.rs#L126

and https://github.com/uni-tue-kn/P4TG/blob/4e98650fb51be319ead0a8b78458f9f1a7d8b13e/Controller/src/core/rate_monitor.rs#L168

the 256 to 512 ?

and test again?

**Comment by yicwang** [comment]
Sure. 0:05am here now. I will do that TMR! Thanks for your really really prompt and awesome help!!!

Regards,
Yichen

**Comment by NE4Y** [comment]
Or even better [c3f052a](https://github.com/uni-tue-kn/P4TG/commit/c3f052a0727891a0057ac738e281a8a1603b1f1c) at dev

**Comment by yicwang** [comment]
Tested on [c3f052a](https://github.com/uni-tue-kn/P4TG/commit/c3f052a0727891a0057ac738e281a8a1603b1f1c) and it seems to be working fine now! Will do more intensive testing today! Thanks again!

**Comment by yicwang** [comment]
No issues so far. Issue can be closed now!
