### ISSUE TITLE
Save config?

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#17]
Hi,

When configuring from UI, is there way to save the config to JSON, and load it back later? Or any quick way to restore configs?

Regards,
Yichen

**Comment by NE4Y** [comment]
The current settings are stored in the local storage of the browser under the keys 

'streams' 'streamSettings' 'port_tx_rx_mapping' and 'gen-mode'

So as long as you do not clear your local storage and use the same browser & url the settings are persistent.

But a real export / import function would be useful.

**Comment by NE4Y** [comment]
As a workaround to switch quickly between different configurations, you could also store the result of `GET /api/trafficgen` (e.g., via Postman) while the generation is running, and use that as the body for `POST /api/trafficgen`

![Bildschirmfoto 2024-03-14 um 20 13 39](https://github.com/uni-tue-kn/P4TG/assets/7404984/f880c4c4-b41c-4494-940d-72300ec9cfb1)

**Comment by yicwang** [comment]
> As a workaround to switch quickly between different configurations, you could also store the result of `GET /api/trafficgen` (e.g., via Postman) while the generation is running, and use that as the body for `POST /api/trafficgen`
> 
> ![Bildschirmfoto 2024-03-14 um 20 13 39](https://private-user-images.githubusercontent.com/7404984/312968407-f880c4c4-b41c-4494-940d-72300ec9cfb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDgxMjMsIm5iZiI6MTcxMDQ0NzgyMywicGF0aCI6Ii83NDA0OTg0LzMxMjk2ODQwNy1mODgwYzRjNC1iNDFjLTQ0OTQtOTQwZC03MjMwMGVjOWNmYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMjAyMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVlMzk2NmQ3N2NjOTllZjVjNTYwMzUzYTg0NjI1YWViMGMyMzhkNWQ0NzI5OTkzYzgyOTMyNGEzYmU4ODA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ao8y9Ahqa8G0MZlLdWdwhX-eYhN2qmVmKy88mFg3HN0)
> 
> This will start the traffic generation. The UI basically does the same and constructs the json body that is returned by `GET /api/trafficgen` from the different local storage values.

I will try this. For now, changing Gbps to Mpps mode takes me a lot of time, and I need to toggle UI many times. This will save my time and make my life much easier.

Regards,
Yichen

**Comment by NE4Y** [comment]
There is now a preliminary import/export function on the settings site. The export button exports the currently saved settings as json.

![Bildschirmfoto 2024-03-15 um 13 08 42](https://github.com/uni-tue-kn/P4TG/assets/7404984/a4540973-954e-4bf3-bff1-577ea5c11b80)

and also some bug fixes for the analyze mode regarding ARP handling (required re-compilation of the data plane).

Implemented in [7bce638](https://github.com/uni-tue-kn/P4TG/commit/7bce6388027a707eca4a894c82f8041f2d1ff05a) at dev (requires re-compilation of the data plane)

**Comment by yicwang** [comment]
That's cool. I am going to just use the POST call directly, will try the new feature later! Thanks!

Regards,
Yichen
