### ISSUE TITLE
VLAN support

### ISSUE THREAD

**Issue by rubensfig** [uni-tue-kn/P4TG#2]
Hello!

Thank you for the good software :)

I would like to add support for generating double tagged VLAN headers.

I have added the files for creating the VLAN headers, currently only hardcoded, so no options available from the gui.

Wrt header calculation, where would I need to add the byte data?

**Comment by rubensfig** [comment]
I have created the following patch, https://github.com/rubensfig/P4TG/commit/c215b72bf4ebc7973e7ea6419051c0612a9544cf. 

Thank you in advance!

**Comment by NE4Y** [comment]
Hi @rubensfig,

Thanks for that suggestion. I will have a look at it and see if we can also integrate it into the GUI.
If I see correctly, you added the tos declaration in the IPv4 header in the TrafficGen method. Is there a reason for that? The tos value is overwritten in the egress pipeline in the Header_Replace control.

What do you mean wrt to the header calculation? The frames should have the L2 size as specified in the GUI - including all headers.

**Comment by NE4Y** [comment]
We added VLAN and QinQ support in 16b3a75.
