### ISSUE TITLE
Failed to get port list?

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#6]
Hi,

I am trying out the project today. The hardware is a Tofino 1 with 4 pipes 65 ports. It is installed with SONiC, and it requires the p4 program to be "switch". So I changed the p4tg.conf to use "switch" as the p4_program name, and also change the main.rs to look for "switch" instead of "traffic_gen". With above small hacks I am able to bring the controller up running.

When I am navigating the UI, and seems the ports/ and settings/ pages are not loading. The RUST server is throwing below:
[2024-02-28T00:25:44Z WARN  p4tg_controller::api::server] Error from REST API: PortNotFound { name: "64" }

So I am looking at the code, and couldn't find out what exactly the API is doing. Can you help with some ideas about what could be wrong here?

Thanks very much!

Regards,
Yichen

**Comment by yicwang** [comment]
Hi Steffen,

Thanks for the prompt reply. So this chip (BFN-T10-064Q) has 65 * 100Gbps ports as below. When you say Port 64 I assume you mean "port id 64", and that port indeed is an internal port on our HW, i.e. not front panel.

I tried your patch, and it works!

Thanks a lot!!!

Regards,
Yichen

**Comment by NE4Y** [comment]
Great to hear. Added the initial port clearance in [9e301ca](https://github.com/uni-tue-kn/P4TG/commit/9e301ca9fd198d999903093fd2a31027db186729)
