### ISSUE TITLE
Some small feedback.

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#7]
Hi,

With quite some hacks, I finally brought the setup up! Just some of my two cents:

1. We can allow the dynamic port initialization.
Today, the port used for tg and loopback are hardcoded in main.rs. Actually that part of code can be exposed out to controller to better configure the ports to fit the physical connection. It is not a big deal, as I can just hack the main.rs and go from there;

2. In the stream configuration UI, the SRC/DST IP ranges has two blocks. After tcpdump, I realized that is FROM/TO instead of IP/MASK. The default of the second is 0.0.0.0 which confused me. Maybe add a "Range" prompt or something like that to reduce the confusion;

Thanks very much!

Regards,
Yichen

**Comment by NE4Y** [comment]
Hi Yichen,

thanks for the feedback!

1.) That's a good point. We should also allow to use more than 10 TG ports on Tofino systems with 64 ports (there, traffic generation with 20 ports should be possible).

2.) The second value (that is by default 0.0.0.0) is actually a randomization mask. For example, if you set the src/dst value to 0.10.20.1 and the mask to 255.0.0.0 you can randomize the first octet of the address. In the dataplane, a 32 bit random number is generated, bitwise ANDed with the randomization mask and the result is bitwise ORed with the corresponding IP src/dst. We should definitely add a description in the UI for that fields.

**Comment by yicwang** [comment]
For (2), ah that is a randomization mask. I am wrong even after tcpdump. Now I got it! Thanks!!

**Comment by NE4Y** [comment]
1) Its now possible to specify the used TG ports in `Controller/config.json` (max 10). Afterward, it may be necessary to reset the settings in the UI (Settings -> Reset). Its also possible to set the p4 program name in an environment variable `P4_NAME` (see docker-compose file).

2) The UI now also has some additional explanations for different features (see question mark icon).

Now in master [2c10231](https://github.com/uni-tue-kn/P4TG/commit/2c10231c64ba7a8f676805156afccd15ca053bea)

**Comment by yicwang** [comment]
Great. I think it has all features that I need for my project so far. I will use it for some time, and I am very happy to promote this project to more use cases in our company!

**Comment by NE4Y** [comment]
Great to hear! Let me know if further features are needed.
