### ISSUE TITLE
Ethernet MACs cannot be multicast addresses when doing randomization

### ISSUE THREAD

**Issue by yicwang** [uni-tue-kn/P4TG#9]
The UI will automatically pick (randomize) MAC addresses used for SMAC, however the algorithm cannot be pure random, as multicast address cannot be used for SMAC.

![image](https://github.com/uni-tue-kn/P4TG/assets/9436025/8596ad2a-a806-4b1a-9d50-1df47a9ff5c5)

**Comment by NE4Y** [comment]
Done in ec50ce5510cacb0e6f2fc283c240a9aa4074eb1a and 1c2b0ef049262377ee11e63c97f0a0438c858fc4.
